# This is based off of reading the actual source code of the bot. :/
# https://github.com/tunnckoCore/triage-new-issues/blob/master/src/index.js#L7
#
# While this file is currently a no-op, it serves the purpose of
# documenting that this bot is indeed being used, since this is a
# non-standard probot bot.
label: "Please triage this"
