# Based on the `python-app.yml` template from GitHub actions:
# https://github.com/actions/starter-workflows/blob/main/ci/python-app.yml
#
# Adapted by Diego Ramirez.

name: Python application tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # windows is strangely failing, so avoid it by now
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10.0-alpha - 3.10"] # all the versions intended for text-formatter

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print('Current Python version:', sys.version)"
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install flake8 isort
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test the imports with isort
      run: |
        # try to check every Python file with isort,
        # those inside folders:
        isort **/*.py --check-only -v
        # but also outside the folders:
        isort *.py --check-only -v
    - name: Finalize the test
      run: python -c "print('Process completed succesfully!')"
